name: Running psalm

on:
  push:
    paths:
      - '**.php'
      - 'psalm.xml'

jobs:
  psalm:
    name: psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github
